### ISSUE TITLE
[Feature Request] Default support for NESPAD by Xgaming?

### ISSUE THREAD

**Issue by Hedda** [kodi-game/controller-topology-project#3]
Please consider adding default support for the "NESPAD", which is a new cross-platform gamepad in extended SNES/NES/N64 retro-style combo by Xgaming of X-Arcade fame.

http://shop.xgaming.com/products/nes-wireless-gamepad-ios-android-mac

I read that Shawn Walters shawn@xgaming.com from Xgaming donated an Tankstick (XArcade) to @garbear before and bet they donate NESPADs too if asked ;)

**Comment by Hedda** [comment]
Looks like the NESPAD by Xgaming is a OEM version and re-branding of  the "NES30 PRO" by 8Bitdo.

http://8bitdo.com/nes30pro/

8Bitdo have this gamepad and many other replica and Nintendo inspired gamepads:

http://8bitdo.com

Perhaps a good idea for Team Kodi to try to get sponsorship deals with both Xgaming & 8Bitdo?

**Comment by garbear** [comment]
Xgaming has already "sponsored" this project in a way, they sent me a dual arcade Tankstick and are the reason we have support for devices using keyboard drivers

This repo is actually exclusively for controllers of emulated game consoles. The mapping is from physical controllers to emulated ones. In this case, the NESPAD is a physical controller that emulates SNES/NES/N64. So SNES/NES/N64 get controller profiles, and for everything else, the "Kodi" controller profile exists.

The "Kodi" controller profile is the fallback. The strategy in this case is to map every physical controller to the "Kodi" controller, and then map the "Kodi" controller to everything that is emulated. Otherwise, we'd be mapping every physical controller to every emulated one. Imagine how much extra data this would be. So because the "Kodi" profile exists, we don't need one for the NESPAD.

Does that make sense?

**Comment by garbear** [comment]
Update on the TankStick support: I've finished the driver and created a snappy icon:

https://github.com/kodi-game/peripheral.xarcade

The open source driver it's based on only runs on linux. Still, that exposes the entire OpenELEC/LibreELEC ecosystem to native tankstick support.

**Comment by Hedda** [comment]
@garbear Aweome awesomeness garbear! Can't wait for reactions when this hits Kodi mainline someday ;)

**Comment by garbear** [comment]
We now ship the Tankstick driver on Linux. It can be enabled in the add-on manager.

**Comment by Hedda** [comment]
You are truley awesomeness incarnate @garbear Thank you!
